spring.application.name=wallet-app
spring.profiles.default=dev
server.port=${PORT:8080}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
app.attachments.max-file-size=${APP_ATTACHMENTS_MAX_FILE_SIZE:5MB}
spring.servlet.multipart.max-file-size=${app.attachments.max-file-size}
spring.servlet.multipart.max-request-size=${app.attachments.max-file-size}

logging.level.com.wallet=INFO
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
