server.port=${SERVER_PORT:7000}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/wallet-dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

app.jwt.secret=${APP_JWT_SECRET:wallet-app-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm}
