package com.wallet.walletapp.notification;

public enum NotificationType {
    TRANSACTION_CREATED,
    PASSWORD_RESET_REQUEST,
    WALLET_DAILY_LIMIT_NEAR,
    WALLET_DAILY_LIMIT_EXCEEDED,
    WALLET_MONTHLY_LIMIT_NEAR,
    WALLET_MONTHLY_LIMIT_EXCEEDED
}
